version: "3.8"

services:
  mysql:
    image: mysql:8.0.43-debian
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: products_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  spring-api:
    image: spring-api-image
    container_name: spring-api-container
    depends_on:
      - mysql
    environment:
      DB_URL: jdbc:mysql://mysql:3306/products_db
      USER_DB: root
      PASSWORD_DB: 1234
    ports:
      - "8080:8080"

volumes:
  mysql_data:
